
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormatSymbols;
import java.time.LocalDate;
import java.time.Month;
import javafx.scene.chart.BarChart;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ridisha Shetty
 */
public class Chart extends javax.swing.JFrame {

    /**
     * Creates new form Chart
     */
    public Chart() {
        initComponents();
        Point center = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        int windowWidth = this.getWidth();
        int windowHeight = this.getHeight();
        this.setBounds(center.x - windowWidth / 2, center.y - windowHeight / 2, windowWidth,
            windowHeight);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the  Editor.
     */
    @SuppressWarnings("unchecked")
    String url = "jdbc:sqlserver://192.168.0.98:1433;databaseName=hostel;integratedSecurity=true";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pagePanel = new javax.swing.JPanel();
        pane = new javax.swing.JPanel();
        home = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHART");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pagePanel.setBackground(new java.awt.Color(238, 255, 237));

        pane.setBackground(new java.awt.Color(244, 244, 244));
        pane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monthly Resident Enrollment", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("ST Copperplate", 0, 18))); // NOI18N

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        home.setPreferredSize(new java.awt.Dimension(22, 22));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pagePanelLayout = new javax.swing.GroupLayout(pagePanel);
        pagePanel.setLayout(pagePanelLayout);
        pagePanelLayout.setHorizontalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pagePanelLayout.setVerticalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ImageIcon icon=new ImageIcon("images/home.png");
        Image img=icon.getImage();
        Image newimg=img.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        ImageIcon finale=new ImageIcon(newimg);
        home.setIcon(finale);
        
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            Statement stmt=con.createStatement();
            
            String sql="select count(*) from resident where joinFrom is not null group by month(joinFrom)";
            ResultSet rs1=stmt.executeQuery(sql);
            int count_m=0;
            while(rs1.next())
            {
                count_m++;
            }
            //System.out.println(count_m);
            if(count_m<=12)
            {
                pane.setLayout(new BoxLayout(pane, BoxLayout.X_AXIS));
                pane.add(Box.createVerticalGlue());
                
                //int n=0;
                String q="select count(*) AS num, month(joinFrom) AS mth, year(joinFrom) AS yr from resident where joinFrom is not null group by month(joinFrom), year(joinFrom)";
                ResultSet rs2=stmt.executeQuery(q);
                while(rs2.next())
                {
                    JPanel contain=new JPanel();
                    contain.setLayout(new BoxLayout(contain, BoxLayout.Y_AXIS));
                    contain.add(Box.createHorizontalGlue());
                    
                    String m=Month.of(rs2.getInt("mth")).name();
                    String mn=m.substring(0,3);
                    //n++;
                    Font f=new Font("Tw Cen MT Condensed", Font.PLAIN, 13);
                    String din=mn+"/";
                    String year=Integer.toString(rs2.getInt("yr"));
                    JLabel l=new JLabel("<html>"+din+"<br/>"+year+"</html>");
                    l.setFont(f);
                    l.setAlignmentX(Component.TOP_ALIGNMENT);
                    
                    int height=rs2.getInt("num")*10;
                    JPanel jp=new JPanel();
                    jp.setBackground(new Color(0,102,0));
                    jp.setMaximumSize(new Dimension( 30, height ));
                    //jp.add(new JLabel("2"));
                    jp.setAlignmentX(Component.TOP_ALIGNMENT);
                    contain.setBackground(new Color(244,244,244));
                    JLabel no=new JLabel(Integer.toString(rs2.getInt("num")));
                    no.setForeground(new Color(0,102,0));
                    
                    contain.add(no);
                    contain.add(jp);
                    contain.add(l);
                    //contain.add(Box.createRigidArea(new Dimension(0, 0)));
                    contain.setAlignmentY(Component.BOTTOM_ALIGNMENT);
                    pane.add(contain);
                }
            }
            else
            {
                pane.setLayout(new BoxLayout(pane, BoxLayout.X_AXIS));
                pane.add(Box.createVerticalGlue());
        
                //only display last 12 months
                //JOptionPane.showMessageDialog(pagePanel, "boo");
                String complex="SELECT * FROM \n" +
                            "(select top 12 * from \n" +
                            "(\n" +
                            "select count(*) as num,\n" +
                            "year(joinFrom) as yr,\n" +
                            "month(joinFrom) as mt\n" +
                            "from resident\n" +
                            "where houseStatus='1'\n" +
                            "group by month(joinFrom), year(joinFrom)\n" +
                            ") w\n" +
                            "order by yr desc,mt desc\n" +
                            ")r order by yr, mt asc";
                
                ResultSet don=stmt.executeQuery(complex);
                while(don.next())
                {
                    JPanel contain=new JPanel();
                    contain.setLayout(new BoxLayout(contain, BoxLayout.Y_AXIS));
                    contain.add(Box.createHorizontalGlue());
                    
                    String m=Month.of(don.getInt("mt")).name();
                    String mn=m.substring(0,3);
                    //n++;
                    Font f=new Font("Tw Cen MT Condensed", Font.PLAIN, 13);
                    String din=mn+"/";
                    String year=Integer.toString(don.getInt("yr"));
                    JLabel l=new JLabel("<html>"+din+"<br/>"+year+"</html>");
                    l.setForeground(Color.BLACK);
                    l.setFont(f);
                    l.setAlignmentX(Component.TOP_ALIGNMENT);
                    
                    int height=don.getInt("num")*10;
                    JPanel jp=new JPanel();
                    jp.setBackground(new Color(0,102,0));
                    jp.setMaximumSize(new Dimension( 30, height ));
                    jp.setAlignmentX(Component.TOP_ALIGNMENT);
                    contain.setBackground(new Color(244,244,244));
                    contain.add(l);
                    contain.add(jp);
                    //contain.add(Box.createRigidArea(new Dimension(0, 0)));
                    
                    contain.setAlignmentY(Component.BOTTOM_ALIGNMENT);
                    pane.add(contain);
                }
            }
            pane.revalidate();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chart().setVisible(true);
            }
        });
    }

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pagePanel;
    private javax.swing.JPanel pane;
    // End of variables declaration//GEN-END:variables
}
