
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ridisha Shetty
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        Point center = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        int windowWidth = this.getWidth();
        int windowHeight = this.getHeight();
        this.setBounds(center.x - windowWidth / 2, center.y - windowHeight / 2, windowWidth,
            windowHeight);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagePanel = new javax.swing.JPanel();
        availBox = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        leftText = new javax.swing.JLabel();
        rent = new javax.swing.JLabel();
        studentBox = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studText = new javax.swing.JLabel();
        totalBox = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        roomText = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        routine = new javax.swing.JLabel();
        room = new javax.swing.JLabel();
        kitchen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTable();
        bill = new javax.swing.JLabel();
        rightBlock = new javax.swing.JPanel();
        leftBlock = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        reports = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        fee = new javax.swing.JLabel();
        staff = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DASHBOARD");
        setBackground(new java.awt.Color(255, 255, 255));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pagePanel.setBackground(new java.awt.Color(238, 255, 237));
        pagePanel.setAutoscrolls(true);
        pagePanel.setPreferredSize(new java.awt.Dimension(472, 588));

        availBox.setBackground(new java.awt.Color(0, 204, 0));
        availBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        availBox.setPreferredSize(new java.awt.Dimension(150, 122));
        availBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availBoxMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel4.setText("AVAILABLE");

        leftText.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        leftText.setText("0");

        javax.swing.GroupLayout availBoxLayout = new javax.swing.GroupLayout(availBox);
        availBox.setLayout(availBoxLayout);
        availBoxLayout.setHorizontalGroup(
            availBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availBoxLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(availBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leftText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        availBoxLayout.setVerticalGroup(
            availBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, availBoxLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(leftText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        rent.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        rent.setForeground(new java.awt.Color(0, 51, 255));
        rent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rent.setText("Rent Payment");
        rent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentMouseClicked(evt);
            }
        });

        studentBox.setBackground(new java.awt.Color(190, 185, 193));
        studentBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        studentBox.setPreferredSize(new java.awt.Dimension(150, 0));
        studentBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentBoxMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel1.setText("STUDENTS");

        studText.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        studText.setText("0");

        javax.swing.GroupLayout studentBoxLayout = new javax.swing.GroupLayout(studentBox);
        studentBox.setLayout(studentBoxLayout);
        studentBoxLayout.setHorizontalGroup(
            studentBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentBoxLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(studentBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentBoxLayout.setVerticalGroup(
            studentBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        totalBox.setBackground(new java.awt.Color(255, 204, 0));
        totalBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totalBox.setPreferredSize(new java.awt.Dimension(170, 122));
        totalBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalBoxMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel2.setText("TOTAL SPACE");

        roomText.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        roomText.setText("0");

        javax.swing.GroupLayout totalBoxLayout = new javax.swing.GroupLayout(totalBox);
        totalBox.setLayout(totalBoxLayout);
        totalBoxLayout.setHorizontalGroup(
            totalBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalBoxLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(totalBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roomText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        totalBoxLayout.setVerticalGroup(
            totalBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roomText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        dashboard.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        routine.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        routine.setForeground(new java.awt.Color(0, 51, 255));
        routine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        routine.setText("Routine Check");
        routine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                routineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                routineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                routineMouseExited(evt);
            }
        });

        room.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        room.setForeground(new java.awt.Color(0, 51, 255));
        room.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        room.setText("Room Distribution");
        room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomMouseClicked(evt);
            }
        });

        kitchen.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        kitchen.setForeground(new java.awt.Color(0, 51, 255));
        kitchen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kitchen.setText("Kitchen Materials");
        kitchen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitchenMouseClicked(evt);
            }
        });

        content.setBackground(new java.awt.Color(238, 255, 237));
        content.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        content.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        content.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(content);

        bill.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        bill.setForeground(new java.awt.Color(0, 51, 255));
        bill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bill.setText("Pay Bill");
        bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billMouseClicked(evt);
            }
        });

        rightBlock.setBackground(new java.awt.Color(238, 255, 237));

        javax.swing.GroupLayout rightBlockLayout = new javax.swing.GroupLayout(rightBlock);
        rightBlock.setLayout(rightBlockLayout);
        rightBlockLayout.setHorizontalGroup(
            rightBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        rightBlockLayout.setVerticalGroup(
            rightBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        leftBlock.setBackground(new java.awt.Color(238, 255, 237));

        javax.swing.GroupLayout leftBlockLayout = new javax.swing.GroupLayout(leftBlock);
        leftBlock.setLayout(leftBlockLayout);
        leftBlockLayout.setHorizontalGroup(
            leftBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        leftBlockLayout.setVerticalGroup(
            leftBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Enrollment Graph");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Diversity Graph");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Profit/Loss");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Food Choice");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        reports.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        reports.setForeground(new java.awt.Color(0, 51, 255));
        reports.setText("Add Reports");
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
        });

        profile.setPreferredSize(new java.awt.Dimension(34, 14));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });

        fee.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        fee.setForeground(new java.awt.Color(0, 51, 255));
        fee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fee.setText("Fee Details");
        fee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feeMouseClicked(evt);
            }
        });

        staff.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        staff.setForeground(new java.awt.Color(0, 51, 255));
        staff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staff.setText("Staff Manage");
        staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pagePanelLayout = new javax.swing.GroupLayout(pagePanel);
        pagePanel.setLayout(pagePanelLayout);
        pagePanelLayout.setHorizontalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagePanelLayout.createSequentialGroup()
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pagePanelLayout.createSequentialGroup()
                                .addComponent(leftBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rightBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                            .addGroup(pagePanelLayout.createSequentialGroup()
                                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dashboard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(routine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(room)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kitchen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bill)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reports)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(staff)))))
                .addContainerGap())
            .addGroup(pagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studentBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(availBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pagePanelLayout.setVerticalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dashboard)
                        .addComponent(routine)
                        .addComponent(room)
                        .addComponent(rent)
                        .addComponent(kitchen)
                        .addComponent(bill)
                        .addComponent(reports)
                        .addComponent(fee)
                        .addComponent(staff)))
                .addGap(18, 18, 18)
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(availBox, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(studentBox, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(totalBox, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(leftBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String url = "jdbc:sqlserver://192.168.0.98:1433;databaseName=hostel;integratedSecurity=true";
    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void routineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routineMouseClicked
        // TODO add your handling code here:
        new RoutineCheck().setVisible(true);
        dispose();
    }//GEN-LAST:event_routineMouseClicked

    private void roomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomMouseClicked
        // TODO add your handling code here:
        new RoomDistribution().setVisible(true);
        dispose();
    }//GEN-LAST:event_roomMouseClicked

    private void rentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentMouseClicked
        // TODO add your handling code here:
        new RentPayment().setVisible(true);
        dispose();
    }//GEN-LAST:event_rentMouseClicked

    private void kitchenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitchenMouseClicked
        // TODO add your handling code here:
        new KitchenMaterials().setVisible(true);
        dispose();
    }//GEN-LAST:event_kitchenMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ImageIcon icon=new ImageIcon("images/login.png");
        Image img=icon.getImage();
        Image newimg=img.getScaledInstance(24, 22, java.awt.Image.SCALE_SMOOTH);
        ImageIcon finale=new ImageIcon(newimg);
        profile.setIcon(finale);
        
        content.setVisible(false);
        int stud=0, total=0;
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            Statement stmt=con.createStatement();
            
            String a="SELECT count(*) AS students FROM resident WHERE houseStatus='1'";
            ResultSet rs_a=stmt.executeQuery(a);
            while(rs_a.next())
            {
                stud=rs_a.getInt("students");
            }
            
            String b="SELECT count(*) AS occ FROM resident";
            ResultSet rs_b=stmt.executeQuery(b);
            while(rs_b.next())
            {
                total=rs_b.getInt("occ");
            }
            int left=total-stud;
            
            roomText.setText(Integer.toString(total));
            studText.setText(Integer.toString(stud));
            leftText.setText(Integer.toString(left));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void studentBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentBoxMouseClicked
        // TODO add your handling code here:
        content.setShowHorizontalLines(true);
        content.setShowVerticalLines(true);
        
        rightBlock.removeAll();
        rightBlock.updateUI();
        leftBlock.removeAll();
        leftBlock.updateUI();
        String head[]={"Name","Room","Joined On","Birthday","Mobile"};
        DefaultTableModel dtm=new DefaultTableModel(head,0);
        JTable tbl=new JTable(dtm);
        
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            Statement stmt=con.createStatement();
            
            String qry="SELECT * FROM resident WHERE houseStatus='1' order by floorNo, flatNo, person";
            ResultSet rs=stmt.executeQuery(qry);
            
            String stay,birth,join;
            LocalDate ldBirth, ldJoin;
            while(rs.next())
            {
                ldJoin=rs.getDate("joinFrom").toLocalDate();
                ldBirth=rs.getDate("birthday").toLocalDate();
                birth=ldBirth.toString();
                join=ldJoin.toString();
                
                stay=Integer.toString(rs.getInt("floorNo"))+"0"+Integer.toString(rs.getInt("flatNo"))+rs.getString("person");
                //System.out.println(rs.getInt("mobile"));
                String[] item={rs.getString("name"),stay,join,birth,rs.getString("mobile")};
                
                dtm.addRow(item);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        content.setVisible(true);
        content.setModel(dtm);
    }//GEN-LAST:event_studentBoxMouseClicked

    private void totalBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalBoxMouseClicked
        // TODO add your handling code here:  
        String floor="SELECT max(floorNo) AS totalFloor FROM resident";
        String flat="SELECT max(flatNo) AS totalFlat FROM resident";
        Font f=new Font("Tw Cen MT Condensed", Font.BOLD, 16);
        int floorno=0, flatno=0;
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            Statement stmt=con.createStatement();
            
            ResultSet rs1=stmt.executeQuery(floor);
            while(rs1.next())
            {
                floorno=rs1.getInt("totalFloor");
            }
            
            ResultSet rs2=stmt.executeQuery(flat);
            while(rs2.next())
            {
                flatno=rs2.getInt("totalFlat");
            }
            int rows=flatno*floorno;
            rightBlock.removeAll();
            rightBlock.updateUI();
            leftBlock.removeAll();
            leftBlock.updateUI();
            content.setVisible(false);
            
            leftBlock.setLayout(new GridLayout(rows,4));   //(rows[3*3], cols[a-d], hspace, vspace)
            rightBlock.setLayout(new GridLayout(rows,4));
            for(int i=1;i<=floorno;i++)
            {
                for(int j=1;j<=flatno;j++)
                {
                    for(char k='a';k<='d';k++)
                    {
                        String in="SELECT * FROM resident WHERE floorNo='"+i+"' AND flatNo='"+j+"' AND person='"+k+"'";
                        ResultSet res=stmt.executeQuery(in);
                        if(res.next())
                        {
                                if(i<=4) //standard -->yellow
                                {
                                    JPanel pd=new JPanel();
                                    pd.setBackground(new Color(248,196,14));
                                    pd.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
                                    JLabel lb=new JLabel(i+"0"+j+k);
                                    lb.setForeground(Color.white);

                                    lb.setFont(f);
                                    pd.add(lb);
                                    
                                    leftBlock.add(pd);
                                }
                                else if(i>5) //deluxe -->red
                                {
                                        JPanel pd=new JPanel();
                                        pd.setBackground(Color.RED);
                                        pd.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
                                        JLabel lb=new JLabel(i+"0"+j+k);
                                        lb.setForeground(Color.white);

                                        lb.setFont(f);
                                        pd.add(lb);
                                        rightBlock.add(pd);
                                }
                                else    //premium   -->blue
                                {
                                        JPanel pd=new JPanel();
                                        pd.setBackground(new Color(119,113,244));
                                        pd.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
                                        JLabel lb=new JLabel(i+"0"+j+k);
                                        lb.setForeground(Color.white);

                                        lb.setFont(f);
                                        pd.add(lb);
                                        rightBlock.add(pd);
                                }
                        }
                        else
                        {
                            JPanel pd=new JPanel();
                            pd.setBackground(new Color(238,255,237));
                            JLabel lb=new JLabel("");
                            lb.setForeground(Color.white);

                            lb.setFont(f);
                            pd.add(lb);
                            leftBlock.add(pd);
                        }
                    }
                }
                leftBlock.revalidate();
                leftBlock.repaint();
                rightBlock.revalidate();
                rightBlock.repaint();
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_totalBoxMouseClicked

    private void billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMouseClicked
        // TODO add your handling code here:
        new BillPayment().setVisible(true);
        dispose();
    }//GEN-LAST:event_billMouseClicked

    private void availBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availBoxMouseClicked
        // TODO add your handling code here:
        
        String floor="SELECT max(floorNo) AS totalFloor FROM resident";
        String flat="SELECT max(flatNo) AS totalFlat FROM resident";
        Font f=new Font("Tw Cen MT Condensed", Font.BOLD, 16);
        
        int floorno=0, flatno=0;
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            Statement stmt=con.createStatement();
            
            ResultSet rs1=stmt.executeQuery(floor);
            while(rs1.next())
            {
                floorno=rs1.getInt("totalFloor");
            }
            
            ResultSet rs2=stmt.executeQuery(flat);
            while(rs2.next())
            {
                flatno=rs2.getInt("totalFlat");
            }
            int rows=floorno*flatno;
            
            content.setVisible(false);
            leftBlock.removeAll();
            leftBlock.updateUI();
            rightBlock.removeAll();
            rightBlock.updateUI();
            
            leftBlock.setLayout(new GridLayout(rows,4));   //(rows[3*3], cols[a-d])
            rightBlock.setLayout(new GridLayout(rows,4));
            for(int i=1;i<=floorno;i++)
            {
                for(int j=1;j<=flatno;j++)
                {
                    for(char k='a';k<='d';k++)
                    {
                        String h="SELECT * FROM resident WHERE floorNo='"+i+"' AND flatNo='"+j+"' AND person='"+k+"'";
                        ResultSet op=stmt.executeQuery(h);
                        
                        if(op.next())
                        {
                            if(op.getObject("name")==null)  //green
                            {
                                if(i<=4)
                                {
                                    JPanel pd=new JPanel();
                                    pd.setBackground(new Color(0,204,0));
                                    pd.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
                                    JLabel lb=new JLabel(i+"0"+j+k);
                                    lb.setForeground(Color.white);

                                    lb.setFont(f);
                                    pd.add(lb);
                                    
                                    leftBlock.add(pd);
                                }
                                else
                                {
                                        JPanel pd=new JPanel();
                                        pd.setBackground(new Color(0,204,0));
                                        pd.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
                                        JLabel lb=new JLabel(i+"0"+j+k);
                                        lb.setForeground(Color.white);

                                        lb.setFont(f);
                                        pd.add(lb);
                                        rightBlock.add(pd);
                                }
                            }
                            else    //gray
                            {
                                JPanel pd=new JPanel();
                                pd.setBackground(new Color(194,186,199));
                                pd.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
                                JLabel lb=new JLabel(i+"0"+j+k);
                                lb.setForeground(Color.white);
                                lb.setFont(f);
                                pd.add(lb);
                                if(i<=4)
                                {
                                    leftBlock.add(pd);
                                }
                                else
                                {
                                    rightBlock.add(pd);
                                }
                            }
                        }
                        else
                        {
                            JPanel p=new JPanel();
                            p.setBackground(new Color(238,255,237));
                            JLabel l=new JLabel("");
                            
                            p.add(l);
                            leftBlock.add(p);
                        }
                    }
                }
                rightBlock.revalidate();
                rightBlock.repaint();
                leftBlock.revalidate();
                leftBlock.repaint();
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_availBoxMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(content, "hello");
        new Chart().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Diversity().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new Stats().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new foodChart().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
        // TODO add your handling code here:
        new Reports().setVisible(true);
        dispose();
    }//GEN-LAST:event_reportsMouseClicked

    private void routineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routineMouseEntered
        // TODO add your handling code here:
   /*     Font f_on=new Font("Yu Gothic", Font.BOLD, 12);
        routine.setFont(f_on);
        routine.setForeground(Color.black);
        
        Font f_off=new Font("Yu Gothic", Font.PLAIN, 12);
        dashboard.setFont(f_off);
        dashboard.setForeground(new Color(0,51,255));   */
    }//GEN-LAST:event_routineMouseEntered

    private void routineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routineMouseExited
        // TODO add your handling code here:
     /*   Font f_off=new Font("Yu Gothic", Font.PLAIN, 12);
        routine.setFont(f_off);
        routine.setForeground(new Color(0,51,255));
        
        Font f_on=new Font("Yu Gothic", Font.BOLD, 12);
        dashboard.setFont(f_on);
        dashboard.setForeground(Color.black);   */
    }//GEN-LAST:event_routineMouseExited

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void feeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feeMouseClicked
        // TODO add your handling code here:
        new Fees().setVisible(true);
        dispose();
    }//GEN-LAST:event_feeMouseClicked

    private void staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffMouseClicked
        // TODO add your handling code here:
        new Staff().setVisible(true);
        dispose();
    }//GEN-LAST:event_staffMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel availBox;
    private javax.swing.JLabel bill;
    private javax.swing.JTable content;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel fee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kitchen;
    private javax.swing.JPanel leftBlock;
    private javax.swing.JLabel leftText;
    private javax.swing.JPanel pagePanel;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel rent;
    private javax.swing.JLabel reports;
    private javax.swing.JPanel rightBlock;
    private javax.swing.JLabel room;
    private javax.swing.JLabel roomText;
    private javax.swing.JLabel routine;
    private javax.swing.JLabel staff;
    private javax.swing.JLabel studText;
    private javax.swing.JPanel studentBox;
    private javax.swing.JPanel totalBox;
    // End of variables declaration//GEN-END:variables
}

