
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Month;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ridisha Shetty
 */
public class foodChart extends javax.swing.JFrame {

    /**
     * Creates new form foodChart
     */
    public foodChart() {
        initComponents();
        Point center = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        int windowWidth = this.getWidth();
        int windowHeight = this.getHeight();
        this.setBounds(center.x - windowWidth / 2, center.y - windowHeight / 2, windowWidth,
            windowHeight);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    String url = "jdbc:sqlserver://192.168.0.98:1433;databaseName=hostel;integratedSecurity=true";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pane = new javax.swing.JPanel();
        home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 255, 237));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(238, 255, 237));

        pane.setBackground(new java.awt.Color(244, 244, 244));
        pane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Choice", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("ST Copperplate", 0, 18))); // NOI18N
        pane.setPreferredSize(new java.awt.Dimension(464, 262));

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        home.setPreferredSize(new java.awt.Dimension(25, 25));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ImageIcon icon=new ImageIcon("images/home.png");
        Image img=icon.getImage();
        Image newimg=img.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        ImageIcon finale=new ImageIcon(newimg);
        home.setIcon(finale);
        
        //////display resident chart of who opted out, for veg and non-veg
        String get="SELECT count(*) AS total, (SELECT count(*) FROM resident WHERE food='veg') AS veg,\n" +
                "(SELECT count(*) FROM resident WHERE food='nonveg') AS nonveg,\n" +
                "(SELECT count(*) FROM resident WHERE food='none') AS notSel\n" +
                "FROM resident WHERE houseStatus='1'";
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            Statement stmt=con.createStatement();
            
            int total=0, veg=0, nonveg=0, none=0;
            ResultSet rs=stmt.executeQuery(get);
            if(rs.next())
            {
                total=rs.getInt("total");
                veg=rs.getInt("veg");
                nonveg=rs.getInt("nonveg");
                none=rs.getInt("notSel");
            }
            //System.out.println(total+" | "+veg+" | "+nonveg+" | "+none);
            /////////////////////////////////////////////
            pane.setLayout(new BoxLayout(pane, BoxLayout.X_AXIS));
            pane.add(Box.createVerticalGlue());
            Font f=new Font("Tw Cen MT Condensed", Font.PLAIN, 18);
                
                    JPanel space=new JPanel();
                    space.setPreferredSize(new Dimension( 30, 1 ));
                    space.setBackground(new Color(244,244,244));
                    //pane.add(space);pane.add(space);
                    
                    JPanel containV=new JPanel();
                    containV.setLayout(new BoxLayout(containV, BoxLayout.Y_AXIS));
                    containV.add(Box.createHorizontalGlue());
                    JLabel jveg=new JLabel("<html>Veg:<br/>"+veg+"/"+total+"</html>");
                    jveg.setFont(f);
                    JPanel jpV=new JPanel();
                    jpV.setBackground(Color.GREEN);
                    jpV.setMaximumSize(new Dimension( 50, veg*4 ));
                    jpV.setAlignmentX(Component.TOP_ALIGNMENT);
                    containV.setBackground(new Color(244,244,244));
                    containV.add(jveg);
                    containV.add(jpV);
                    containV.setAlignmentY(Component.BOTTOM_ALIGNMENT);
                    pane.add(containV);
                    pane.add(space);
                    
                    JPanel containN=new JPanel();
                    containN.setLayout(new BoxLayout(containN, BoxLayout.Y_AXIS));
                    containN.add(Box.createHorizontalGlue());
                    JLabel jnonveg=new JLabel("<html>Non-Veg:<br/>"+nonveg+"/"+total+"</html>");
                    jnonveg.setFont(f);
                    JPanel jpN=new JPanel();
                    jpN.setBackground(Color.RED);
                    jpN.setMaximumSize(new Dimension( 50, nonveg*4 ));
                    jpN.setAlignmentX(Component.TOP_ALIGNMENT);
                    containN.setBackground(new Color(244,244,244));
                    containN.add(jnonveg);
                    containN.add(jpN);
                    containN.setAlignmentY(Component.BOTTOM_ALIGNMENT);
                    pane.add(containN);
                    
                    JPanel containO=new JPanel();
                    containO.setLayout(new BoxLayout(containO, BoxLayout.Y_AXIS));
                    containO.add(Box.createHorizontalGlue());
                    JLabel jOut=new JLabel("<html>Opted out:<br/>"+none+"/"+total+"</html>");
                    jOut.setFont(f);
                    JPanel jpO=new JPanel();
                    jpO.setBackground(Color.GRAY);
                    jpO.setMaximumSize(new Dimension( 50, none*4 ));
                    jpO.setAlignmentX(Component.TOP_ALIGNMENT);
                    containO.setBackground(new Color(244,244,244));
                    containO.add(jOut);
                    containO.add(jpO);
                    containO.setAlignmentY(Component.BOTTOM_ALIGNMENT);
                    pane.add(containO);
                    
                    pane.repaint();
                    //////////////////////////
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodChart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pane;
    // End of variables declaration//GEN-END:variables
}
