
import java.awt.Container;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ridisha Shetty
 */
public class RedFlag extends javax.swing.JFrame {

    /**
     * Creates new form RedFlag
     */
    public RedFlag() {
        initComponents();
        Point center = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        int windowWidth = this.getWidth();
        int windowHeight = this.getHeight();
        this.setBounds(center.x - windowWidth / 2, center.y - windowHeight / 2, windowWidth,
            windowHeight);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    String url = "jdbc:sqlserver://192.168.0.98:1433;databaseName=hostel;integratedSecurity=true";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagePanel = new javax.swing.JPanel();
        removeBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        roomField = new javax.swing.JTextField();
        numRemove = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOfContents = new javax.swing.JTable();
        detailBtn = new javax.swing.JButton();
        home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RED FLAGS");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pagePanel.setBackground(new java.awt.Color(238, 255, 237));
        pagePanel.setPreferredSize(new java.awt.Dimension(472, 363));

        removeBtn.setBackground(new java.awt.Color(255, 255, 255));
        removeBtn.setForeground(new java.awt.Color(0, 102, 0));
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Flag Serial No. to Delete:");

        roomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Room No:");

        tableOfContents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOfContents.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(tableOfContents);

        detailBtn.setBackground(new java.awt.Color(255, 255, 255));
        detailBtn.setForeground(new java.awt.Color(0, 102, 0));
        detailBtn.setText("Details");
        detailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailBtnMouseClicked(evt);
            }
        });
        detailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBtnActionPerformed(evt);
            }
        });

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pagePanelLayout = new javax.swing.GroupLayout(pagePanel);
        pagePanel.setLayout(pagePanelLayout);
        pagePanelLayout.setHorizontalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pagePanelLayout.createSequentialGroup()
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(pagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(detailBtn))
                    .addGroup(pagePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(roomField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pagePanelLayout.setVerticalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        removeBtn.getAccessibleContext().setAccessibleName("Remove Flags");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomFieldActionPerformed

    private void detailBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailBtnMouseClicked
        // TODO add your handling code here:
        String room=roomField.getText();
        String divide[]=room.split("");
        
        if(room.matches("[1-3]0[1-3][abcd]"))
        {
            String[] tblHead={"Sr No.","Red Flag No.","Check Out At","Check In At"};
            DefaultTableModel dtm=new DefaultTableModel(tblHead,0);
            JTable tbl=new JTable(dtm);
            
            try
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection(url);
                Statement st=con.createStatement();
                String qry="SELECT * FROM redFlags WHERE studentID=(SELECT srNo FROM resident WHERE floorNo='"+divide[0]+"' and flatNo='"+divide[2]+"' and person='"+divide[3]+"')";
                
                ResultSet rs=st.executeQuery(qry);
                int k=1;
                
                LocalTime lt_in, lt_out;
                LocalDate when, ld_in, ld_out;
                LocalTime ten=LocalTime.parse("22:00:00");
                
                while(rs.next())
                {
                    
                    if(rs.getTime("checkIn")==null || rs.getDate("checkIn")==null)    
                    {}
                    else
                    {
                        lt_in=rs.getTime("checkIn").toLocalTime();
                        lt_out=rs.getTime("checkOut").toLocalTime();
                        ld_in=rs.getDate("checkIn").toLocalDate();
                        ld_out=rs.getDate("checkOut").toLocalDate();
                        if(lt_in.isAfter(ten))
                        {
                            when=rs.getDate("checkOut").toLocalDate();
                            int date=when.getDayOfMonth();
                            int month=when.getMonthValue();
                            int year=when.getYear();
                            String form=date+"-"+month+"-"+year;
                            String[] item={Integer.toString(k),Integer.toString(rs.getInt("serialNo")),lt_out.toString(),lt_in.toString()};
                            dtm.addRow(item);
                            k++;
                        }
                        else if(ld_in.isAfter(ld_out))
                        {
                            when=rs.getDate("checkOut").toLocalDate();
                            int date=when.getDayOfMonth();
                            int month=when.getMonthValue();
                            int year=when.getYear();
                            String form=date+"-"+month+"-"+year;
                            String[] item={Integer.toString(k),Integer.toString(rs.getInt("serialNo")),ld_out.toString(),ld_in.toString()};
                            dtm.addRow(item);
                            k++;
                        }
                    }
                }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            tableOfContents.setModel(dtm);
        }
        else
        {
            JOptionPane.showMessageDialog(tableOfContents, "Invalid room no.");
        }
    }//GEN-LAST:event_detailBtnMouseClicked

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        if(numRemove.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(removeBtn, "Enter a flag no. to remove");
        }
        else
        {
            int num=Integer.parseInt(numRemove.getText());
            String msg="", naam="";
            try
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection(url);
                Statement st=con.createStatement();
                
                String sel="SELECT * FROM resident WHERE srNo=(SELECT studentID FROM redFlags WHERE serialNo='"+num+"')";
                ResultSet res=st.executeQuery(sel);
                if(res.next())
                {
                    naam=res.getString("name");
                }
                
                msg="Are you sure you want to remove "+naam+"'s flag~"+num+"?";
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
            
            int reply=JOptionPane.showConfirmDialog(removeBtn, msg, "head", JOptionPane.YES_NO_OPTION);
            if(reply == JOptionPane.YES_OPTION)
            {
                try
                {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection con = DriverManager.getConnection(url);
                    Statement st=con.createStatement();
                    String rem="DELETE FROM redFlags WHERE serialNo='"+num+"'";

                    int j=st.executeUpdate(rem);
                    if(j>0)
                    {
                        JOptionPane.showMessageDialog(removeBtn, "Removed successfully");
                        new RedFlag().setVisible(true);
                        dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(removeBtn, "No entry found");
                    }
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(pagePanel, "ds");
        ImageIcon icon=new ImageIcon("images/home.png");
        Image img=icon.getImage();
        Image newimg=img.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        ImageIcon finale=new ImageIcon(newimg);
        home.setIcon(finale);
    }//GEN-LAST:event_formComponentShown

    private void detailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedFlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedFlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedFlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedFlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RedFlag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailBtn;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numRemove;
    private javax.swing.JPanel pagePanel;
    private javax.swing.JButton removeBtn;
    private javax.swing.JTextField roomField;
    private javax.swing.JTable tableOfContents;
    // End of variables declaration//GEN-END:variables
}
